const hospitals = [
  {
    Hospital_ID: 'H001',
    Hospital_Name: 'City Care Hospital',
    City: 'Pune',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H002',
    Hospital_Name: 'Sunrise Multispecialty Hospital',
    City: 'Pune',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H003',
    Hospital_Name: 'Ruby Health Center',
    City: 'Pune',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H004',
    Hospital_Name: 'Metro Hospital',
    City: 'Mumbai',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H005',
    Hospital_Name: 'Lifeline Hospital',
    City: 'Mumbai',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H006',
    Hospital_Name: 'Green Valley Hospital',
    City: 'Mumbai',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H007',
    Hospital_Name: 'Apollo East Clinic',
    City: 'Bengaluru',
    State: 'Karnataka',
  },
  {
    Hospital_ID: 'H008',
    Hospital_Name: 'Harmony Hospital',
    City: 'Bengaluru',
    State: 'Karnataka',
  },
  {
    Hospital_ID: 'H009',
    Hospital_Name: 'Nova Specialty Center',
    City: 'Hyderabad',
    State: 'Telangana',
  },
  {
    Hospital_ID: 'H010',
    Hospital_Name: 'Medistar Hospital',
    City: 'Hyderabad',
    State: 'Telangana',
  },
];

const doctors = [
  {
    Doctor_ID: 'D001',
    Doctor_Name: 'Dr. Amit Shah',
    Specialty: 'Cardiology',
    Rating: 4.8,
    Availability: true,
  },
  {
    Doctor_ID: 'D002',
    Doctor_Name: 'Dr. Neha Kulkarni',
    Specialty: 'Dermatology',
    Rating: 4.5,
    Availability: true,
  },
  {
    Doctor_ID: 'D003',
    Doctor_Name: 'Dr. Raj Mehta',
    Specialty: 'Orthopedics',
    Rating: 4.7,
    Availability: false,
  },
  {
    Doctor_ID: 'D004',
    Doctor_Name: 'Dr. Priya Nair',
    Specialty: 'Pediatrics',
    Rating: 4.9,
    Availability: true,
  },
  {
    Doctor_ID: 'D005',
    Doctor_Name: 'Dr. Karan Verma',
    Specialty: 'Neurology',
    Rating: 4.6,
    Availability: true,
  },
  {
    Doctor_ID: 'D006',
    Doctor_Name: 'Dr. Sneha Iyer',
    Specialty: 'Gynecology',
    Rating: 4.4,
    Availability: true,
  },
  {
    Doctor_ID: 'D007',
    Doctor_Name: 'Dr. Rahul Patil',
    Specialty: 'General Medicine',
    Rating: 4.3,
    Availability: false,
  },
  {
    Doctor_ID: 'D008',
    Doctor_Name: 'Dr. Anjali Deshmukh',
    Specialty: 'ENT',
    Rating: 4.7,
    Availability: true,
  },
  {
    Doctor_ID: 'D009',
    Doctor_Name: 'Dr. Vikram Rao',
    Specialty: 'Oncology',
    Rating: 4.8,
    Availability: true,
  },
  {
    Doctor_ID: 'D010',
    Doctor_Name: 'Dr. Pooja Sen',
    Specialty: 'Ophthalmology',
    Rating: 4.5,
    Availability: false,
  },
  {
    Doctor_ID: 'D011',
    Doctor_Name: 'Dr. Nitin Joshi',
    Specialty: 'Cardiology',
    Rating: 4.6,
    Availability: true,
  },
  {
    Doctor_ID: 'D012',
    Doctor_Name: 'Dr. Shreya Kapoor',
    Specialty: 'Pediatrics',
    Rating: 4.9,
    Availability: true,
  },
  {
    Doctor_ID: 'D013',
    Doctor_Name: 'Dr. Sameer Khan',
    Specialty: 'Orthopedics',
    Rating: 4.4,
    Availability: false,
  },
  {
    Doctor_ID: 'D014',
    Doctor_Name: 'Dr. Meenal Gupta',
    Specialty: 'Dermatology',
    Rating: 4.7,
    Availability: true,
  },
  {
    Doctor_ID: 'D015',
    Doctor_Name: 'Dr. Arjun Reddy',
    Specialty: 'General Medicine',
    Rating: 4.5,
    Availability: true,
  },
];

module.exports = {
  hospitals,
  doctors,
};