const hospitals = [
  {
    Hospital_ID: 'H001',
    Hospital_Name: 'City Care Hospital',
    City: 'Pune',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H002',
    Hospital_Name: 'Sunrise Multispecialty Hospital',
    City: 'Pune',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H003',
    Hospital_Name: 'Ruby Health Center',
    City: 'Pune',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H004',
    Hospital_Name: 'Metro Hospital',
    City: 'Mumbai',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H005',
    Hospital_Name: 'Lifeline Hospital',
    City: 'Mumbai',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H006',
    Hospital_Name: 'Green Valley Hospital',
    City: 'Mumbai',
    State: 'Maharashtra',
  },
  {
    Hospital_ID: 'H007',
    Hospital_Name: 'Apollo East Clinic',
    City: 'Bengaluru',
    State: 'Karnataka',
  },
  {
    Hospital_ID: 'H008',
    Hospital_Name: 'Harmony Hospital',
    City: 'Bengaluru',
    State: 'Karnataka',
  },
  {
    Hospital_ID: 'H009',
    Hospital_Name: 'Nova Specialty Center',
    City: 'Hyderabad',
    State: 'Telangana',
  },
  {
    Hospital_ID: 'H010',
    Hospital_Name: 'Medistar Hospital',
    City: 'Hyderabad',
    State: 'Telangana',
  },
];

const doctors = [
  {
    Doctor_ID: 'D001',
    Doctor_Name: 'Dr. Amit Shah',
    Specialty: 'Cardiology',
    Hospital_ID: 'H001',
    Rating: 4.8,
    Availability: true,
    schedule: [{ day: '2026-05-18', timings: ['10AM to 12PM', '5PM to 9PM'] }, { day: '2026-05-19', timings: ['10AM to 3PM'] }],
  },
  {
    Doctor_ID: 'D002',
    Doctor_Name: 'Dr. Neha Kulkarni',
    Specialty: 'Dermatology',
    Hospital_ID: 'H002',
    Rating: 4.5,
    Availability: true,
    schedule: [{ day: '2026-05-20', timings: ['9AM to 1PM'] }, { day: '2026-05-22', timings: ['4PM to 8PM'] }],
  },
  {
    Doctor_ID: 'D003',
    Doctor_Name: 'Dr. Raj Mehta',
    Specialty: 'Orthopedics',
    Hospital_ID: 'H003',
    Rating: 4.7,
    Availability: false,
    schedule: [{ day: '2026-05-21', timings: ['11AM to 4PM'] }, { day: '2026-05-23', timings: ['10AM to 2PM'] }],
  },
  {
    Doctor_ID: 'D004',
    Doctor_Name: 'Dr. Priya Nair',
    Specialty: 'Pediatrics',
    Hospital_ID: 'H004',
    Rating: 4.9,
    Availability: true,
    schedule: [{ day: '2026-05-18', timings: ['8AM to 12PM'] }, { day: '2026-05-20', timings: ['2PM to 6PM'] }],
  },
  {
    Doctor_ID: 'D005',
    Doctor_Name: 'Dr. Karan Verma',
    Specialty: 'Neurology',
    Hospital_ID: 'H005',
    Rating: 4.6,
    Availability: true,
    schedule: [{ day: '2026-05-19', timings: ['10AM to 1PM'] }, { day: '2026-05-21', timings: ['3PM to 7PM'] }],
  },
  {
    Doctor_ID: 'D006',
    Doctor_Name: 'Dr. Sneha Iyer',
    Specialty: 'Gynecology',
    Hospital_ID: 'H006',
    Rating: 4.4,
    Availability: true,
    schedule: [{ day: '2026-05-18', timings: ['10AM to 12PM', '5PM to 9PM'] }, { day: '2026-05-19', timings: ['10AM to 3PM'] }],
  },
  {
    Doctor_ID: 'D007',
    Doctor_Name: 'Dr. Rahul Patil',
    Specialty: 'General Medicine',
    Hospital_ID: 'H007',
    Rating: 4.3,
    Availability: false,
    schedule: [{ day: '2026-05-20', timings: ['9AM to 1PM'] }, { day: '2026-05-22', timings: ['4PM to 8PM'] }],
  },
  {
    Doctor_ID: 'D008',
    Doctor_Name: 'Dr. Anjali Deshmukh',
    Specialty: 'ENT',
    Hospital_ID: 'H008',
    Rating: 4.7,
    Availability: true,
    schedule: [{ day: '2026-05-21', timings: ['11AM to 4PM'] }, { day: '2026-05-23', timings: ['10AM to 2PM'] }],
  },
  {
    Doctor_ID: 'D009',
    Doctor_Name: 'Dr. Vikram Rao',
    Specialty: 'Oncology',
    Hospital_ID: 'H009',
    Rating: 4.8,
    Availability: true,
    schedule: [{ day: '2026-05-18', timings: ['8AM to 12PM'] }, { day: '2026-05-20', timings: ['2PM to 6PM'] }],
  },
  {
    Doctor_ID: 'D010',
    Doctor_Name: 'Dr. Pooja Sen',
    Specialty: 'Ophthalmology',
    Hospital_ID: 'H010',
    Rating: 4.5,
    Availability: false,
    schedule: [{ day: '2026-05-19', timings: ['10AM to 1PM'] }, { day: '2026-05-21', timings: ['3PM to 7PM'] }],
  },
  {
    Doctor_ID: 'D011',
    Doctor_Name: 'Dr. Nitin Joshi',
    Specialty: 'Cardiology',
    Hospital_ID: 'H001',
    Rating: 4.6,
    Availability: true,
    schedule: [{ day: '2026-05-18', timings: ['10AM to 12PM', '5PM to 9PM'] }, { day: '2026-05-19', timings: ['10AM to 3PM'] }],
  },
  {
    Doctor_ID: 'D012',
    Doctor_Name: 'Dr. Shreya Kapoor',
    Specialty: 'Pediatrics',
    Hospital_ID: 'H002',
    Rating: 4.9,
    Availability: true,
    schedule: [{ day: '2026-05-20', timings: ['9AM to 1PM'] }, { day: '2026-05-22', timings: ['4PM to 8PM'] }],
  },
  {
    Doctor_ID: 'D013',
    Doctor_Name: 'Dr. Sameer Khan',
    Specialty: 'Orthopedics',
    Hospital_ID: 'H003',
    Rating: 4.4,
    Availability: false,
    schedule: [{ day: '2026-05-21', timings: ['11AM to 4PM'] }, { day: '2026-05-23', timings: ['10AM to 2PM'] }],
  },
  {
    Doctor_ID: 'D014',
    Doctor_Name: 'Dr. Meenal Gupta',
    Specialty: 'Dermatology',
    Hospital_ID: 'H004',
    Rating: 4.7,
    Availability: true,
    schedule: [{ day: '2026-05-18', timings: ['8AM to 12PM'] }, { day: '2026-05-20', timings: ['2PM to 6PM'] }],
  },
  {
    Doctor_ID: 'D015',
    Doctor_Name: 'Dr. Arjun Reddy',
    Specialty: 'General Medicine',
    Hospital_ID: 'H005',
    Rating: 4.5,
    Availability: true,
    schedule: [{ day: '2026-05-19', timings: ['10AM to 1PM'] }, { day: '2026-05-21', timings: ['3PM to 7PM'] }],
  },
];

const patients = [
  {
    Patient_ID: 'P001',
    FullName: 'Rahul Sharma',
    MobileNumber: '9876543210',
    DateOfBirth: new Date('1985-06-15'),
    City: 'Pune',
    PreferredLanguage: 'Hindi',
  },
  {
    Patient_ID: 'P002',
    FullName: 'Priya Desai',
    MobileNumber: '8765432109',
    DateOfBirth: new Date('1992-11-20'),
    City: 'Mumbai',
    PreferredLanguage: 'English',
  },
];

const admins = [
  {
    username: 'admin',
    password: 'password123',
  },
];

module.exports = {
  hospitals,
  doctors,
  patients,
  admins,
};
